backend:
  name: git-gateway
  branch: main

media_folder: "images/blog/uploads"
public_folder: "/images/blog/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Cover Image", name: "cover_image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }